export const metadata = {
  title: "SubDomainLayout",
  description: "Generated by create next app",
};
const SubDomainLayout = ({ children }) => {
  return children;
};

export default SubDomainLayout;
